version: "3.8"

services:
  postgres:
    image: postgres:15  
    container_name: postgres_pokemon
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: ash
      POSTGRES_PASSWORD: pikachu
      POSTGRES_DB: pokemon_cards
    volumes:
      - ./squirtle/respaldo:/home/respaldo
      - ./squirtle/bash/inicio.sh:/docker-entrypoint-initdb.d/inicio.sh
    restart: always
    
  bulbasaur-back:
    build: ./bulbasaur
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://ash:pikachu@postgres:5432/pokemon_cards
    restart: always



